name: blog
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: ">=3.3.3 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    bot_toast: ^4.1.3
    cupertino_icons: ^1.0.6
    connectivity_plus: ^6.0.2
    dio: ^5.4.3+1
    flutter_html: ^3.0.0-beta.2
    flutter_svg: ^2.0.10+1
    get: ^4.6.6
    image_gallery_saver: ^2.0.3
    lottie: ^3.1.0
    path_provider: ^2.1.3
    permission_handler: ^11.3.1
    pull_to_refresh: ^2.0.0
    shared_preferences: ^2.2.2
    url_launcher: ^6.2.5
    window_manager: ^0.3.8
    share: ^2.0.4
    # windows下面不能用
    webview_flutter: ^2.0.12

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^3.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/images/3.0x/
        - assets/svg/
        - assets/lottie/lottie_common_load.json
        - assets/lottie/page_loading_anim.json
        - assets/lottie/refresh_footer.json
        - assets/lottie/refresh_head_loading.json
        - assets/lottie/refresh_empty_page.json
        - assets/lottie/refresh_error.json
        - assets/lottie/collect_success.json
